# Generated by Django 3.1.6 on 2021-04-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'MNE MANAGER'), (2, 'STAFF USER'), (3, 'ZONAL CORDINATOR'), (4, 'CHAIRPERSON'), (5, 'CLUB LEADER'), (6, 'MEMBER'), (7, 'ADMIN')], default=6, null=True),
        ),
    ]
