# Generated by Django 3.2.4 on 2021-06-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.IntegerField()),
                ('tel', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('tb_suspect', models.BooleanField(default=None)),
                ('tb_status', models.BooleanField(default=None)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
    ]
