# Generated by Django 3.1.6 on 2021-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('sex', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('agreed_screening', models.BooleanField(default=None)),
                ('tb_suspect', models.BooleanField(default=None)),
                ('sputum_collection', models.BooleanField(default=None)),
                ('tb_status', models.BooleanField(default=None)),
                ('referal', models.BooleanField(default=None)),
                ('refered_hospital', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment_status', models.BooleanField(default=None)),
            ],
        ),
    ]
