# Generated by Django 3.1.6 on 2021-06-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agreed_screening',
        ),
        migrations.RemoveField(
            model_name='client',
            name='referal',
        ),
        migrations.RemoveField(
            model_name='client',
            name='refered_hospital',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sputum_collection',
        ),
        migrations.RemoveField(
            model_name='client',
            name='treatment_status',
        ),
    ]
