# Generated by Django 3.2.4 on 2021-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
