# Generated by Django 3.1.6 on 2021-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210509_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(default='Active', max_length=31, verbose_name='Status'),
        ),
    ]
