# Generated by Django 3.1.6 on 2021-06-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memberProfile', serialize=False, to='account.customuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CHAIRMAN'), (2, 'ASS. CHAIR'), (3, 'SECRETARY'), (4, 'ASS_SECRETARY'), (5, 'TREASURER'), (6, 'MEMBER')], default=6, null=True)),
                ('status', models.CharField(default='Domant', max_length=31, verbose_name='status')),
                ('fee_status', models.CharField(default='Not Paid', max_length=31, verbose_name='fee status')),
                ('tel', models.CharField(max_length=31, verbose_name='Phone Number')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='club.club')),
            ],
        ),
    ]
