# Generated by Django 3.1.6 on 2021-05-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210505_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='Tel',
            new_name='tel',
        ),
    ]
