# Generated by Django 3.2.4 on 2022-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20220228_1304'),
        ('member', '0002_memberprofile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='activity.Activity'),
        ),
    ]
