# Generated by Django 3.2.4 on 2021-06-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conducted', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberprofile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitytype')),
            ],
        ),
    ]
