# Generated by Django 3.2.4 on 2021-06-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
