# Generated by Django 3.1.6 on 2021-04-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Club Name')),
                ('health_facility', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('sub_district', models.CharField(blank=True, max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.supervisor')),
            ],
        ),
    ]
