# Generated by Django 3.1.6 on 2021-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
