# Generated by Django 3.1.6 on 2021-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210426_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='office',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
