# Generated by Django 3.1.6 on 2021-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
    ]
